compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y flex bison nasm genisoimage qemu libgmp10 lib32gmp-dev libmpfr4 lib32mpfr-dev libmpc2 libmpc-dev
script: make toolchain-x86 && make all && make isoimage
